-- SEU ZE

SHOW DATABASES;

DROP DATABASE PROJETO;

create database projeto;

USE PROJETO;

-- SISTEMA DO SEU ZE

CREATE TABLE CLIENTE(

	ID_CLIENTE VARCHAR(11) NOT NULL,
	TELEFONE VARCHAR(11)

);

CREATE TABLE CARRO(
	
	IDCLIENTE VARCHAR(11) NOT NULL,
	MARCA VARCHAR(30) NOT NULL

);


CREATE TABLE CORES(
	
	IDCLIENTE VARCHAR(11) NOT NULL,
	CORES VARCHAR(30) NOT NULL

);

ALTER TABLE CLIENTE ADD CONSTRAINT
CPF_CLIENTE PRIMARY KEY(ID_CLIENTE);

ALTER TABLE CARRO ADD CONSTRAINT
CPF_CLIENTE_CARRO FOREIGN KEY(IDCLIENTE)
REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE CORES ADD CONSTRAINT
CPF_CLIENTE_CORES FOREIGN KEY(IDCLIENTE)
REFERENCES CLIENTE(ID_CLIENTE);

-- TABELAS
SHOW CREATE TABLE CLIENTE;
SHOW CREATE TABLE CORES;
SHOW CREATE TABLE CARRO;

-- INSERCAO REGISTROS

INSERT INTO CLIENTE VALUES(12345678910,NULL);


