/*FUNCOES DE AGREGACAO NUMERICAS */

CREATE TABLE VENDEDORES(
IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30),
SEXO CHAR(1),
JANEIRO FLOAT(10,2),
FEVEREIRO FLOAT(10,2),
MARCO FLOAT(10,2)

);

INSERT INTO VENDEDORES VALUES(NULL,
'CARLOS','M',313.2,24344.3,2344.3);
INSERT INTO VENDEDORES VALUES(NULL,
'CARL','M',313.2,24344.3,2344.3);
INSERT INTO VENDEDORES VALUES(NULL,
'CAOS','M',313.2,24344.3,2344.3);
INSERT INTO VENDEDORES VALUES(NULL,
'JOAO','M',313.2,2444.3,2344.3);
INSERT INTO VENDEDORES VALUES(NULL,
'CLARA','F',33.2,243,2344.3);
INSERT INTO VENDEDORES VALUES(NULL,
'CARLA','F',31.2,244.3,2.3);


/* FUNCAO MAX E MIN */

SELECT MAX(FEVEREIRO) AS MAIOR_FEV FROM VENDEDORES;
SELECT MIN(FEVEREIRO) AS MAIOR_FEV FROM VENDEDORES;

/*MEDIA AVERAGE */

SELECT AVG(FEVEREIRO) AS MEDIA_FEV
 FROM VENDEDORES;
 
 /*TODOS COM TRUNCATE */
 
SELECT MAX(FEVEREIRO),
 MIN(FEVEREIRO) AS MAIOR_FEV, 
 TRUNCATE(AVG(FEVEREIRO),2) AS MEDIA_FEV
 FROM VENDEDORES
