/* aula tipos nulos | tupla é uma linha, ou um registro inteiro*/

/*mostrando as tabelas */

show tables;

/*exibindo estrutura de uma tabela */

desc cliente;

/* SINTAXE BASICA DE INSERCAO - INSERT INTO... */
/* forma 1 - excluindo colunas */


INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,
'2293110','MAIA LACERDA - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,
'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,
'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');
 
/* forma 2 - colocando colunas (mais segura)*/

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF)VALUES(
'LILIAN','F','SENADOR SOARES - TIJUCA
 - RIO DE JANEIRO - RJ','947785696',887774856);
 
 /* FORMA 4 - INSERTE COMPACTO - SOMENTE MYSQL */
 
 INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,
 '548556985','PRES ANTIONIO CARLOS - CENTRO - 
 SAO PAULO - SP'),('CARLA','F','CARLA@TERATI.COM.BR',
 7745828,'66587458','SAMUEL SILVA - 
 CENTRO - BELO HORIZONTE - MG');


 
 
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF)VALUES(
'CLARA','F','SENADOR SOARES - TIJUCA
 - RIO DE JANEIRO - RJ','947785696',99999999999);
