/* modelagem básica ENTIDADE=TABELA 
CAMPOS = ATRIBUTOS */

CLIENTE

NOME = CARACTER(30)
CPF = NUMERIC0(11)
EMAIL = CARACTER(30)
TELEFONE = CARACTER(30)
ENDEREÇO = CARACTER(100)
SEXO = CARACTER(1)

/* PROCESSOS DE MODELAGEM /*

/*FASE 1 E FASE 2 PELO ADM DE DADOS /*
/* MODELAGEM CONCEITUAL = Rascunho /*
/* MODELAGEM LOGICA = PROGRAMA DE MODELAGEM /*

/* DBA E AD /*
/* MODELAGEM FISICA =  */
