/* order by */

USE COMERCIO;

CREATE TABLE ALUNOS(
	NUMERO INT,
	NOME VARCHAR(30)
	
);

INSERT INTO ALUNOS VALUES(1,'JOAO');
INSERT INTO ALUNOS VALUES(2,'JANAINA');
INSERT INTO ALUNOS VALUES(3,'ZOE');
INSERT INTO ALUNOS VALUES(4,'MARCELO');
INSERT INTO ALUNOS VALUES(5,'CLARA');
INSERT INTO ALUNOS VALUES(6,'CLARA');
INSERT INTO ALUNOS VALUES(1,'MAFRA');
INSERT INTO ALUNOS VALUES(1,'ANTONIO');
INSERT INTO ALUNOS VALUES(3,'ANA');
INSERT INTO ALUNOS VALUES(2,'BERNADO');
INSERT INTO ALUNOS VALUES(3,'ANNE');

SELECT * FROM ALUNOS ORDER BY 1;
SELECT * FROM ALUNOS ORDER BY 2;

/*ORDERNAR POR MAIS DE UMA COLUNA */

SELECT * FROM ALUNOS ORDER BY NUMERO, NOME;
SELECT * FROM ALUNOS ORDER BY 1, 2;


 /*MESCLAR N PODE USAR INDICE */
 
 SELECT NOME FROM ALUNOS ORDER BY NUMERO, NOME;
 
 /*ASC E DESC*/
 
 SELECT * FROM ALUNOS ORDER BY 1 ASC;
 SELECT * FROM ALUNOS ORDER BY 1 DESC;
 
 SELECT * FROM ALUNOS ORDER BY NUMERO DESC, NOME DESC;
 
 
 SELECT C.NOME,
 C.SEXO,
 IFNULL(C.EMAIL,'*************') AS "EMAIL",
 T.TIPO,
 T.NUMERO,
 E.BAIRRO, 
 E.CIDADE,
 E.ESTADO
FROM CLIENTE C INNER JOIN TELEFONE T
ON C.IDCLIENTE=T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE=E.ID_CLIENTE ORDER BY 1;
