--selecting NULL REGISTERS
SHOW DATABASES;

USE PROJETO;

SHOW TABLES;

SELECT * FROM CLIENTES;

/* deletando registros */
 UPDATE CLIENTE SET TELEFONE = '2293110 - 989345678' WHERE NOME = 'JOAO';
 
 SELECT SEXO, COUNT(*) AS QTD FROM CLIENTE GROUP BY SEXO;
 
 /* PRIMEIRA FORMA NORMAL */
 
 /*
 
 1 - TODO CAMPO VETORIZADO SE TORNA OUTRA TABELA
 
 (EA, FIESTA, UNO) -> ELEMENTOS DA MSM FAMILIA
 
 TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA
 QUANDO O CAMPO FOR DIVISIVEL (VETOR COM ELEMENTOS DE FAMILIAS DIFERENTES)
 
 3- TODA TABELA NECESSITA DE PELO MENOS UM CAMPO 
 QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO UNICO
 (CHAVE PRIMARIA, OU PRIMARY KEY) - CPF POR EXEMPLO

 
 
 */
 
 CREATE DATABASE COMERCIO;
 
 USE COMERCIO;
 
 SHOW DATABASES;
 
 CREATE TABLE CLIENTE(
 
 IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(30) NOT NULL,
 SEXO ENUM('M','F') NOT NULL,
 EMAIL VARCHAR(50) UNIQUE,
 CPF VARCHAR(15) UNIQUE
 
 
 
 );
 
 /* TEM Q SER O MESMO TIPO CHAVE ENTRANGEIRA*/
 
 
 
 CREATE TABLE ENDERECO(
 IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
 RUA VARCHAR(30) NOT NULL,
 BAIRRO VARCHAR(30) NOT NULL,
 CIDADE VARCHAR(30) NOT NULL,
 ESTADO CHAR(2) NOT NULL,
 ID_CLIENTE INT UNIQUE,
 FOREIGN KEY(ID_CLIENTE)
 REFERENCES CLIENTE(IDCLIENTE)
 );
 
 CREATE TABLE TELEFONE(
 
  IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
  TIPO ENUM('RES','COM','CEL') NOT NULL,
  NUMERO VARCHAR(10) NOT NULL,
  ID_CLIENTE INT,
  FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
  
 );
 
 /*FOREIGN E UMA CHAVE PRIMARIA DE UMA TABELA QUE VAI ATE A OUTRAA PARA TRAZER REGISTROS*/
 
 /* EM RELACIONAMENTOS 1X1 A CHAVE ESTRANGEIRA FICA NA TABELA
 MAIS FRACA */
 
 /* em relacionamentos 1xn a chave estrangeira ficara sempre na
 cardinalidade n*/
 
 
 DROP TABLE CLIENTE;
 
 
 
 INSERT INTO CLIENTE VALUES(NULL,'JOAO',
 'M','JOAO@IG.COM','75674757377');
 
  INSERT INTO CLIENTE VALUES(NULL,'CARLOS',
 'M','CARLOS@IG.COM','75666666377');
 
  INSERT INTO CLIENTE VALUES(NULL,'ANA',
 'F','ANA@IG.COM','7567455557377');
 
  INSERT INTO CLIENTE VALUES(NULL,'CLARA',
 'M',NULL,'756747444377');
 
  INSERT INTO CLIENTE VALUES(NULL,'JORGE',
 'M','JORGE@IG.COM','7567433337377');
 
  INSERT INTO CLIENTE VALUES(NULL,'CELIA',
 'F','CELIA@IG.COM','75673457377');
 
 
 
  DESC ENDERECO;
 
 INSERT INTO ENDERECO VALUES(NULL,'RIA ANTONIO SA',
 'CENTRO','BH','MG',4);
 
  INSERT INTO ENDERECO VALUES(NULL,'RIA CAP SA',
 'CENTRO','RJ','RJ',1);
 
  INSERT INTO ENDERECO VALUES(NULL,'RIA PRES SA',
 'CENTRO','SP','SP',3);
 
  
  INSERT INTO ENDERECO VALUES(NULL,'RIA BORA SA',
 'ESTACIO','RJ','RJ',2);
 
  
  INSERT INTO ENDERECO VALUES(NULL,'RIA ALFANDEGA SA',
 'CENTRO','VT','ES',6);
 
  
  INSERT INTO ENDERECO VALUES(NULL,'RIA CEMTRO SA',
 'CENTRO','SA','BA',5);
 
 SELET * FROM ENDERECO;
