 /*o comando select
 selecao projecao e juncao
 */
 
 SELECT NOW() as DATA_HORA, 'FELIPE MAFRA' AS PROFESSOR;
 
 SELECT 'FELIPE MAFRA';
 
 SELECT 'BANCO DE DADS';
 
 /* ALIAS DE COLUNAS | SELECT É COMANDO DE PROJECAO*/
 
 SELECT NOME, SEXO, EMAIL FROM CLIENTE;

 SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
 
 SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
 

 SELECT EMAIL, NOME, SEXO, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;
 
