 /*o comando select
 selecao projecao e juncao
 */
 
 SELECT NOW() as DATA_HORA, 'FELIPE MAFRA' AS PROFESSOR;
 
 SELECT 'FELIPE MAFRA';
 
 SELECT 'BANCO DE DADS';
 
 /* ALIAS DE COLUNAS | SELECT É COMANDO DE PROJECAO*/
 
 SELECT NOME, SEXO, EMAIL FROM CLIENTE;

 SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
 
 SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
 

 SELECT EMAIL, NOME, SEXO, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;
 
 /*SELECAO*/
 
  /*FILTRANDO DADOS COM WHERE E LIKE */
 
 SELECT * FROM CLIENTE;
 
  /*FILTRANDO */
 
 SELECT NOME, SEXO FROM CLIENTE WHERE SEXO='M';
 
 SELECT NOME, ENDERECO FROM CLIENTE WHERE SEXO = 'F';
 
 SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO = 'RJ';
 
 /*UTILIZANDO O LIKE*/
 
 SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE 'RJ';
 
/*CARACTER CORINGA %-> QUALQUER COISA */
 
 SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE '%RJ';
 
 SELECT NOME, ENDERECO,SEXO FROM CLIENTE WHERE ENDERECO LIKE '%RJ';

 SELECT NOME, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE 'OSCAR CURY%';
 
 SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE ENDERECO
 LIKE '%CENTRO%';
 
