
 
 CREATE DATABASE COMERCIO;
 
 USE COMERCIO;
 


/* NOME, EMAIL NUMERO ESTADO */

SELECT C.NOME, C.EMAIL, E.ESTADO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON 
C.IDCLIENTE = E.ID_CLIENTE INNER JOIN
TELEFONE T ON C.IDCLIENTE=T.ID_CLIENTE;


SELECT C.NOME,
 IFNULL(C.EMAIL,'NAO TEM EMAIL'),
 E.ESTADO,
 T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON 
C.IDCLIENTE = E.ID_CLIENTE INNER JOIN
TELEFONE T ON C.IDCLIENTE=T.ID_CLIENTE;


SELECT C.NOME,
 IFNULL(C.EMAIL,'NAO TEM EMAIL') AS 'EMAIL',
 E.ESTADO,
 T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON 
C.IDCLIENTE = E.ID_CLIENTE INNER JOIN
TELEFONE T ON C.IDCLIENTE=T.ID_CLIENTE;
