
 
 CREATE DATABASE COMERCIO;
 
 USE COMERCIO;
 


/* NOME, EMAIL NUMERO ESTADO */

SELECT C.NOME, C.EMAIL, E.ESTADO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON 
C.IDCLIENTE = E.ID_CLIENTE INNER JOIN
TELEFONE T ON C.IDCLIENTE=T.ID_CLIENTE;


SELECT C.NOME,
 IFNULL(C.EMAIL,'NAO TEM EMAIL'),
 E.ESTADO,
 T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON 
C.IDCLIENTE = E.ID_CLIENTE INNER JOIN
TELEFONE T ON C.IDCLIENTE=T.ID_CLIENTE;


SELECT C.NOME,
 IFNULL(C.EMAIL,'NAO TEM EMAIL') AS 'EMAIL',
 E.ESTADO,
 T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON 
C.IDCLIENTE = E.ID_CLIENTE INNER JOIN
TELEFONE T ON C.IDCLIENTE=T.ID_CLIENTE;

/*VIEWS */
SELECT C.NOME,
 C.SEXO,
 C.EMAIL,
 T.TIPO,
 T.NUMERO,
 E.BAIRRO, 
 E.CIDADE,
 E.ESTADO
FROM CLIENTE C INNER JOIN TELEFONE T
ON C.IDCLIENTE=T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE=E.ID_CLIENTE;

CREATE VIEW RELATORIO AS
SELECT C.NOME,
 C.SEXO,
 C.EMAIL,
 T.TIPO,
 T.NUMERO,
 E.BAIRRO, 
 E.CIDADE,
 E.ESTADO
FROM CLIENTE C INNER JOIN TELEFONE T
ON C.IDCLIENTE=T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE=E.ID_CLIENTE;

SELECT * FROM RELATORIO;

/* PREFIXO */

CREATE VIEW V_RELATORIO AS
SELECT C.NOME,
 C.SEXO,
 IFNULL(C.EMAIL,'*************') AS "EMAIL",
 T.TIPO,
 T.NUMERO,
 E.BAIRRO, 
 E.CIDADE,
 E.ESTADO
FROM CLIENTE C INNER JOIN TELEFONE T
ON C.IDCLIENTE=T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE=E.ID_CLIENTE;

SELECT * FROM V_RELATORIO;
