
 
 CREATE DATABASE COMERCIO;
 
 USE COMERCIO;
 


/* NOME, EMAIL NUMERO ESTADO */

SELECT C.NOME, C.EMAIL, E.ESTADO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON 
C.IDCLIENTE = E.ID_CLIENTE INNER JOIN
TELEFONE T ON C.IDCLIENTE=T.ID_CLIENTE;


SELECT C.NOME,
 IFNULL(C.EMAIL,'NAO TEM EMAIL'),
 E.ESTADO,
 T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON 
C.IDCLIENTE = E.ID_CLIENTE INNER JOIN
TELEFONE T ON C.IDCLIENTE=T.ID_CLIENTE;


SELECT C.NOME,
 IFNULL(C.EMAIL,'NAO TEM EMAIL') AS 'EMAIL',
 E.ESTADO,
 T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E ON 
C.IDCLIENTE = E.ID_CLIENTE INNER JOIN
TELEFONE T ON C.IDCLIENTE=T.ID_CLIENTE;

/*VIEWS */
SELECT C.NOME,
 C.SEXO,
 C.EMAIL,
 T.TIPO,
 T.NUMERO,
 E.BAIRRO, 
 E.CIDADE,
 E.ESTADO
FROM CLIENTE C INNER JOIN TELEFONE T
ON C.IDCLIENTE=T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE=E.ID_CLIENTE;

CREATE VIEW RELATORIO AS
SELECT C.NOME,
 C.SEXO,
 C.EMAIL,
 T.TIPO,
 T.NUMERO,
 E.BAIRRO, 
 E.CIDADE,
 E.ESTADO
FROM CLIENTE C INNER JOIN TELEFONE T
ON C.IDCLIENTE=T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE=E.ID_CLIENTE;

SELECT * FROM RELATORIO;

/* PREFIXO */

CREATE VIEW V_RELATORIO AS
SELECT C.NOME,
 C.SEXO,
 IFNULL(C.EMAIL,'*************') AS "EMAIL",
 T.TIPO,
 T.NUMERO,
 E.BAIRRO, 
 E.CIDADE,
 E.ESTADO
FROM CLIENTE C INNER JOIN TELEFONE T
ON C.IDCLIENTE=T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE=E.ID_CLIENTE;

SELECT * FROM V_RELATORIO;

/*OPERACOES DML EM VIEW (UPDATE, INSERT DELETE)*/

INSERT INTO V_RELATORIO VALUES('ANDREIA','F','ANDREIA@UOL.BR',
'CENTRO','VITORIA','ES');

/*PODE FAZER UPDATES EM VIEWS COM JOIN*/

UPDATE V_RELATORIO SET NOME = 'JOSE' WHERE NOME = 'JORGE';


/*PODE FAZER DML EM VIEWS COM JOIN*/

CREATE TABLE JOGADORES(JOGADOR INT,
NOME VARCHAR(30),
ESTADO CHAR(2));




INSERT INTO JOGADORES VALUES(1,'GUERRERO','RS');
INSERT INTO JOGADORES VALUES(2'GABIGOL','RS');
INSERT INTO JOGADORES VALUES(3,'GANSO','RJ');
INSERT INTO JOGADORES VALUES(4,'NENE','RJ');
INSERT INTO JOGADORES VALUES(5,'LOVE','SP');

CREATE VIEW V_JOGADORES AS SELECT NOME, ESTADO FROM JOGADORES;

SELECT * FROM V_JOGADORES;

DELETE FROM V_JOGADORES WHERE NOME = 'GUERRERO';

INSERT INTO V_JOGADORES VALUES('GUERRERO','RS');

SELECT * FROM V_RELATORIO WHERE SEXO = 'F';
