-- COMUNICAÇÃO ENTRE DOIS BANCOS

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTOS(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

STATUS

CREATE DATABASE BACKUP;

USE BACKUP;


CREATE TABLE BKP_PRODUTO(
	IDBKP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

USE LOJA;

INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,1000,'TESTE',0.0);

SELECT * FROM BACKUP.BKP_PRODUTO;


DELIMITER $

CREATE TRIGGER BACKUP_PRODUT
BEFORE INSERT ON PRODUTOS
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP.BKP_PRODUTO VALUES
	(NULL,NEW.IDPRODUTO,NEW.NOME,NEW.VALOR);

END
$

DELIMITER ;

INSERT INTO PRODUTOS VALUES(NULL,'LIVRO',90.0);
INSERT INTO PRODUTOS VALUES(NULL,'LIVRO 1',95.0);
INSERT INTO PRODUTOS VALUES(NULL,'LIVRO 2',550.0);
INSERT INTO PRODUTOS VALUES(NULL,'LIVRO 3',40.0);
INSERT INTO PRODUTOS VALUES(NULL,'LIVRO 4',904.0);



DELIMITER $

CREATE TRIGGER BACKUP_PRODUT_DEL
BEFORE DELETE ON PRODUTOS
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP.BKP_PRODUTO VALUES
	(NULL,OLD.IDPRODUTO,OLD.NOME,OLD.VALOR);

END
$

DELIMITER ;

DROP TRIGGER BACKUP_PRODUT;



DELIMITER $

CREATE TRIGGER BACKUP_PRODUT
AFTER INSERT ON PRODUTOS
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP.BKP_PRODUTO VALUES
	(NULL,NEW.IDPRODUTO,NEW.NOME,NEW.VALOR);

END
$

DELIMITER ;


INSERT INTO PRODUTOS VALUES(NULL,'LIVRO VCSHARP',904.0);
SELECT * FROM BACKUP.BKP_PRODUTO;
SELECT * FROM PRODUTOS;
