/* A 42 TRIGGER DE AUDITORIA */

--

DELIMITER ;

DROP DATABASE LOJA;

DROP DATABASE BACKUP;

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

STATUS

INSERT INTO PRODUTO VALUES(NULL,'LIVRO',90.0);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO 1',95.0);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO 2',550.0);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO 3',40.0);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO 4',904.0);

CREATE DATABASE BACKUP;

USE BACKUP;

CREATE TABLE BKP_PRODUTO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)

);


DELIMITER $

CREATE TRIGGER AUDIT_PROD
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,
	OLD.IDPRODUTO,OLD.NOME,OLD.VALOR,NEW.VALOR,
	NOW(),CURRENT_USER(),"U");

END
$

DELIMITER ;

UPDATE PRODUTO SET VALOR=110.00
WHERE IDPRODUTO = 4;

SELECT * FROM PRODUTO;

SELECT * FROM BACKUP.BKP_PRODUTO-- trigger de auditoria
