-- SEGUNDA E TERCEIRA FORMAS NORMAIS

/*

PRIMEIRA FN

	ATOMIDICADE - CAMPO N PODE SER DIVISIVEL
	UM CAMPO NAO PODE SER VETORIZADO
	PK CHAVE PRIMARIA

  

*/

CREATE DATABASE CONSULTORIO;

USE CONSULTORIO;

CREATE TABLE PACIENTE(

	IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	NASCIMENTO DATE

);


CREATE TABLE MEDICO(

	IDMEDICO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	ESPECIALIDADE VARCHAR(30),
	FUNCIONARIO ENUM('S','N')

);

CREATE TABLE HOSPITAL(

	IDHOSPITAL INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	BAIRRO VARCHAR(30),
	CIDADE VARCHAR(30),
	ESTADO CHAR(2)

);


CREATE TABLE CONSULTA(

	IDCONSULTA INT PRIMARY KEY AUTO_INCREMENT,
	ID_PACIENTE INT,
	ID_MEDICO INT,
	ID_HOSPITAL INT,
	DATA DATETIME,
	DIAGNOSTICO VARCHAR(50)


);

CREATE TABLE INTERNACAO(

	IDINTERNACAO INT PRIMARY KEY AUTO_INCREMENT,
	ENTRADA DATETIME,
	QUARTO INT,
	SAIDA DATETIME,
	OBSERVACOES VARCHAR(50),
	ID_CONSULTA INT UNIQUE

);


-- CRIANDO CONSTRAINTS
ALTER TABLE CONSULTA ADD CONSTRAINT FK_PACIENTE_ID
FOREIGN KEY CONSULTA(ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE); 

ALTER TABLE CONSULTA ADD CONSTRAINT FK_MEDICO_ID
FOREIGN KEY CONSULTA(ID_MEDICO) REFERENCES MEDICO(IDMEDICO);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_HOSPITAL_ID
FOREIGN KEY CONSULTA(ID_HOSPITAL) REFERENCES HOSPITAL(IDHOSPITAL);

ALTER TABLE  INTERNACAO ADD CONSTRAINT FK_INTERNACAO_ID
FOREIGN KEY INTERNACAO(ID_CONSULTA) REFERENCES CONSULTA(IDCONSULTA);


-- DICIONARIO DE DADOS

USE INFORMATION_SCHEMA;

SHOW TABLES;

DESC TABLE_CONSTRAINTS;

SELECT * FROM TABLE_CONSTRAINTS;



