-- AUTORELAACIONAMENTO


CREATE DATABASE AULA44;

USE AULA44;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT,
	VALOR FLOAT(10,2),
	ID_PREREQ INT

);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS(IDCURSO);

INSERT INTO CURSOS VALUES(NULL,'BD RELACIONAL',20,400.0,NULL);
INSERT INTO CURSOS VALUES(NULL,'BUSINESS INTELLIGENCE',20,400.0,1);
INSERT INTO CURSOS VALUES(NULL,'RELATORIOS AVANCADOS',20,400.0,2);
INSERT INTO CURSOS VALUES(NULL,'LOGICA DE PROGRAMACAO',20,400.0,NULL);
INSERT INTO CURSOS VALUES(NULL,'RUBY',20,400.0,4);

SELECT * FROM CURSOS;

SELECT NOME, VALOR, HORAS, IFNULL(ID_PREREQ,"SEM REQ") REQUISITO FROM CURSOS;


/* NOME VALOR NUMERO DE HORAS E NOME DO PRE REQUISITO DO CURSO */

--MY SOLUTION

ALTER TABLE CURSOS ADD NOME_PREREQ VARCHAR(30);

ALTER TABLE CURSOS DROP COLUMN NOME_PREREQ;

CREATE VIEW CURSOS_PREREQ AS SELECT * FROM CURSOS;

SELECT C.NOME FROM CURSOS C
RIGHT JOIN CURSOS_PREREQ CP ON C.IDCURSO=CP.ID_PREREQ;

ALTER TABLE CURSOS ADD NOME_PREREQ VARCHAR(30);

SELECT CP.IDCURSO,CP.NOME,CP.HORAS,CP.VALOR,CP.ID_PREREQ,C.NOME NOME_PREREQ FROM CURSOS C
RIGHT JOIN CURSOS CP ON C.IDCURSO=CP.ID_PREREQ;

CREATE VIEW CURSOS_NAME_PRERQ AS SELECT CP.IDCURSO,CP.NOME,CP.HORAS,CP.VALOR,CP.ID_PREREQ,C.NOME NOME_PREREQ FROM CURSOS C
RIGHT JOIN CURSOS CP ON C.IDCURSO=CP.ID_PREREQ;

-- solucao ideal

SELECT C.NOME CURSO, C.VALOR VALOR,
 C.HORAS CARGA, IFNULL(P.NOME,"---")
AS PREREQ FROM CURSOS C
LEFT JOIN CURSOS P ON P.IDCURSO = C.ID_PREREQ;
